name: app_widget
description: Flutter plugin to manage app widget / home screen widget from within flutter app.
version: 0.3.0
homepage: https://noxasch.tech/
repository: https://github.com/noxasch/flutter_app_widget/tree/master/app_widget
issue_tracker: https://github.com/noxasch/flutter_app_widget/issues

environment:
  sdk: ">=2.17.6 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.7
  app_widget_platform_interface: ^0.3.1
  app_widget_android: ^0.3.2
  # app_widget_platform_interface: # local dev
  #   path: ../app_widget_platform_interface
  # app_widget_android: # local dev
  #   path: ../app_widget_android

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        default_package: app_widget_android
